services:
  mysql-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: onion1!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: onion1!
    ports:
      - "3307:3306"
    volumes:
      - mysql_db_data:/var/lib/mysql
    networks:
      - invest-network

volumes:
  mysql_db_data:

networks:
  invest-network:
